included:
  - Sources
  - Tests
  - Dangerfile.swift

# Rules
disabled_rules:
  - trailing_comma # Conflicts with swift-format's multiElementCollectionTrailingCommas
  - force_cast # Handled by swift-format's NeverForceUnwrap
  - force_try # Handled by swift-format's NeverUseForceTry
  - force_unwrapping # Handled by swift-format's NeverForceUnwrap
  - file_header

opt_in_rules:
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal # Matches swift-format's AlwaysUseLiteralForEmptyCollectionInit
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough # Matches swift-format's NoCasesWithOnlyFallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return # Matches swift-format's OmitExplicitReturns
  - implicitly_unwrapped_optional # Matches swift-format's NeverUseImplicitlyUnwrappedOptionals
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
  - capture_variable
  - explicit_self
  - unused_declaration
  - unused_import

line_length: 150
nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 3
    error: 5
