name: Build, Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Set the fetch-depth > 1 or set to 0 for codecov upload detection
          fetch-depth: 2

      - name: Enable development dependencies
        run: sed -i.bak "s/\/\/dev//g" Package.swift

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Generate Code Coverage
        run: |
          mkdir -p coverage
          xcrun llvm-cov export \
            .build/debug/PostiePackageTests.xctest/Contents/MacOS/PostiePackageTests \
            -instr-profile .build/debug/codecov/default.profdata \
            --format="lcov" \
            --ignore-filename-regex "\\.build" \
            --ignore-filename-regex "Tests" > ./coverage/coverage.lcov

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage.lcov
          name: codecov-umbrella
          flags: unittests
          fail_ci_if_error: true
